export { default as JSicon } from './icons/js.svg'
export { default as CSSicon } from './icons/css.svg'
export { default as SLACKicon } from './icons/slack.svg'
export { default as JENKINSicon } from './icons/jenkins.svg'
export { default as REACTicon } from './icons/reactjs-icon.svg'
export { default as DOCKERicon } from './icons/docker.svg'
export { default as DJANGOicon } from './icons/django.svg'
export { default as GRAFANAicon } from './icons/grafana-icon.svg'
export { default as Linuxicon } from './icons/centos.svg'
export { default as GITHUBicon } from './icons/github.svg'
export { default as GITHUBicon2 } from './icons/github2.png'
export { default as INSTAicon } from './icons/insta.svg'
export { default as STEAMicon } from './icons/steam.svg'
export { default as LINKEDINicon } from './icons/linkedin.svg'


export {default as Harmonya} from './projects/Harmonya.png'
export {default as LoginUI} from './projects/LoginUI.png'
export {default as Cryptos} from './projects/cryptos.png'

