export { default as JSicon } from './js.svg'
export { default as CSSicon } from './css.svg'
export { default as SLACKicon } from './slack.svg'
export { default as JENKINSicon } from './jenkins.svg'
export { default as REACTicon } from './reactjs-icon.svg'
export { default as DOCKERicon } from './docker.svg'
export { default as DJANGOicon } from './django.svg'
export { default as GRAFANAicon } from './grafana-icon.svg'
export { default as Linuxicon } from './centos.svg'
export { default as GITHUBicon } from './github.svg'

